
production:
  clinical.encounters.sequential.list: MEDICAL HISTORY 2,SURGICAL HISTORY,MEDICAL HISTORY
  clinical.encounters.display.list: MENU|MEDICAL HISTORY 2,SURGICAL HISTORY;MEDICAL HISTORY
  scope: SURGICAL HISTORY|TODAY,MENU|TODAY,MEDICAL HISTORY|TODAY,MEDICAL HISTORY 2|EXISTS
  label: MENU|Menu,MEDICAL HISTORY 2|Medical History 2

development:
  clinical.encounters.sequential.list: MEDICAL HISTORY 2,SURGICAL HISTORY,MEDICAL HISTORY
  clinical.encounters.display.list: MENU|MEDICAL HISTORY 2,SURGICAL HISTORY;MEDICAL HISTORY
  scope: SURGICAL HISTORY|TODAY,MENU|TODAY,MEDICAL HISTORY|TODAY,MEDICAL HISTORY 2|EXISTS
  label: MENU|Menu,MEDICAL HISTORY 2|Medical History 2

test: &TEST
  clinical.encounters.sequential.list: MEDICAL HISTORY 2,SURGICAL HISTORY,MEDICAL HISTORY
  clinical.encounters.display.list: MENU|MEDICAL HISTORY 2,SURGICAL HISTORY;MEDICAL HISTORY
  scope: SURGICAL HISTORY|TODAY,MENU|TODAY,MEDICAL HISTORY|TODAY,MEDICAL HISTORY 2|EXISTS
  label: MENU|Menu,MEDICAL HISTORY 2|Medical History 2

