
production:
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY,RAPID ANTIBODY TEST|RECENT,GIVE DRUGS|,PMTCT HISTORY|EXISTS
  concept: DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status,EID VISIT|Weight,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,PMTCT HISTORY|ARVs In Labour
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

development:
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY,RAPID ANTIBODY TEST|RECENT,GIVE DRUGS|,PMTCT HISTORY|EXISTS
  concept: DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status,EID VISIT|Weight,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,PMTCT HISTORY|ARVs In Labour
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

test: &TEST
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY,RAPID ANTIBODY TEST|RECENT,GIVE DRUGS|,PMTCT HISTORY|EXISTS
  concept: DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status,EID VISIT|Weight,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,PMTCT HISTORY|ARVs In Labour
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
