
production:
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,EID VISIT|TODAY,NOTES|,DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,GIVE DRUGS|
  concept: PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

development:
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,EID VISIT|TODAY,NOTES|,DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,GIVE DRUGS|
  concept: PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

test: &TEST
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,EID VISIT|TODAY,NOTES|,DNA PCR TEST|RECENT,ENROLLMENT STATUS|RECENT,GIVE DRUGS|
  concept: PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
