
production:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: GIVE DRUGS|,NOTES|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Age of child
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

development:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: GIVE DRUGS|,NOTES|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Age of child
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

test: &TEST
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: GIVE DRUGS|,NOTES|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Age of child
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

give_drugs: eid_protocol_patients
