
production:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,NOTES|NOTES,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,EID VISIT|EID VISIT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: EID VISIT|TODAY,ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,PMTCT HISTORY|EXISTS,DNA PCR TEST|RECENT,RAPID ANTIBODY TEST|RECENT
  concept: EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status,PMTCT HISTORY|ARVs In Labour,DNA PCR TEST|DNA-PCR Testing Result,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

development:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,NOTES|NOTES,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,EID VISIT|EID VISIT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: EID VISIT|TODAY,ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,PMTCT HISTORY|EXISTS,DNA PCR TEST|RECENT,RAPID ANTIBODY TEST|RECENT
  concept: EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status,PMTCT HISTORY|ARVs In Labour,DNA PCR TEST|DNA-PCR Testing Result,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

test: &TEST
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,NOTES|NOTES,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,EID VISIT|EID VISIT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: EID VISIT|TODAY,ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,PMTCT HISTORY|EXISTS,DNA PCR TEST|RECENT,RAPID ANTIBODY TEST|RECENT
  concept: EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status,PMTCT HISTORY|ARVs In Labour,DNA PCR TEST|DNA-PCR Testing Result,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
