
production:
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,PMTCT HISTORY|EXISTS,EID VISIT|TODAY,NOTES|,GIVE DRUGS|
  concept: ENROLLMENT STATUS|Age of child,PMTCT HISTORY|ARVs In Labour,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

development:
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,PMTCT HISTORY|EXISTS,EID VISIT|TODAY,NOTES|,GIVE DRUGS|
  concept: ENROLLMENT STATUS|Age of child,PMTCT HISTORY|ARVs In Labour,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

test: &TEST
  label.encounter.map: GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,PMTCT HISTORY|EXISTS,EID VISIT|TODAY,NOTES|,GIVE DRUGS|
  concept: ENROLLMENT STATUS|Age of child,PMTCT HISTORY|ARVs In Labour,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

give_drugs: eid_protocol_patients
