
production:
  label.encounter.map: NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,EID VISIT|EID VISIT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,GIVE DRUGS|DISPENSING,DNA PCR TEST|DNA-PCR TEST,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: NOTES|,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT,GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,DNA PCR TEST|RECENT,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,DNA PCR TEST|DNA-PCR Testing Result,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

development:
  label.encounter.map: NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,EID VISIT|EID VISIT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,GIVE DRUGS|DISPENSING,DNA PCR TEST|DNA-PCR TEST,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: NOTES|,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT,GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,DNA PCR TEST|RECENT,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,DNA PCR TEST|DNA-PCR Testing Result,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

test: &TEST
  label.encounter.map: NOTES|NOTES,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,EID VISIT|EID VISIT,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,GIVE DRUGS|DISPENSING,DNA PCR TEST|DNA-PCR TEST,PMTCT HISTORY|PMTCT HISTORY
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: NOTES|,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT,GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,DNA PCR TEST|RECENT,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,DNA PCR TEST|DNA-PCR Testing Result,EID VISIT|Weight
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
