
production:
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

development:
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

test: &TEST
  label.encounter.map: RAPID ANTIBODY TEST|RAPID ANTIBODY TEST,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,GIVE DRUGS|DISPENSING,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,NOTES|NOTES
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,ENROLLMENT STATUS|RECENT
  concept: RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Mother HIV Status
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
