
production:
  clinical.encounters.sequential.list: SURGICAL HISTORY,ANOTHER PATIENT MEDICAL HISTORY,MEDICAL HISTORY
  scope: MEDICAL HISTORY|TODAY,ANOTHER PATIENT MEDICAL HISTORY|EXISTS,SURGICAL HISTORY|TODAY
  label: ANOTHER PATIENT MEDICAL HISTORY|Medical History 2

development:
  clinical.encounters.sequential.list: SURGICAL HISTORY,ANOTHER PATIENT MEDICAL HISTORY,MEDICAL HISTORY
  scope: MEDICAL HISTORY|TODAY,ANOTHER PATIENT MEDICAL HISTORY|EXISTS,SURGICAL HISTORY|TODAY
  label: ANOTHER PATIENT MEDICAL HISTORY|Medical History 2

test: &TEST
  clinical.encounters.sequential.list: SURGICAL HISTORY,ANOTHER PATIENT MEDICAL HISTORY,MEDICAL HISTORY
  scope: MEDICAL HISTORY|TODAY,ANOTHER PATIENT MEDICAL HISTORY|EXISTS,SURGICAL HISTORY|TODAY
  label: ANOTHER PATIENT MEDICAL HISTORY|Medical History 2

