
production:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,GIVE DRUGS|,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Confirmatory HIV test,EID VISIT|Weight
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

development:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,GIVE DRUGS|,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Confirmatory HIV test,EID VISIT|Weight
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

test: &TEST
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,EID VISIT|EID VISIT,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: PMTCT HISTORY|EXISTS,GIVE DRUGS|,ENROLLMENT STATUS|RECENT,NOTES|,EID VISIT|TODAY
  concept: PMTCT HISTORY|ARVs In Labour,ENROLLMENT STATUS|Confirmatory HIV test,EID VISIT|Weight
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

give_drugs: eid_protocol_patients
