
production:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,ENROLLMENT STATUS|RECENT
  concept: DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

development:
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,ENROLLMENT STATUS|RECENT
  concept: DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

test: &TEST
  label.encounter.map: ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,PMTCT HISTORY|PMTCT HISTORY,GIVE DRUGS|DISPENSING,NOTES|NOTES,EID VISIT|EID VISIT,DNA PCR TEST|DNA-PCR TEST,RAPID ANTIBODY TEST|RAPID ANTIBODY TEST
  clinical.encounters.sequential.list: DNA PCR TEST,EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,RAPID ANTIBODY TEST,GIVE DRUGS
  clinical.encounters.display.list: DNA PCR TEST;EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;RAPID ANTIBODY TEST;GIVE DRUGS
  scope: GIVE DRUGS|,DNA PCR TEST|RECENT,PMTCT HISTORY|EXISTS,RAPID ANTIBODY TEST|RECENT,NOTES|,EID VISIT|TODAY,ENROLLMENT STATUS|RECENT
  concept: DNA PCR TEST|DNA-PCR Testing Result,PMTCT HISTORY|ARVs In Labour,RAPID ANTIBODY TEST|Rapid Antibody Testing Sample Date,EID VISIT|Weight,ENROLLMENT STATUS|Mother HIV Status
  label: GIVE DRUGS|Give drugs,ENROLLMENT STATUS|Enrollment Status

dna_pcr_test: eid_protocol_patients

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

rapid_antibody_test: eid_protocol_patients

give_drugs: eid_protocol_patients
