
production:
  label.encounter.map: EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS
  concept: ENROLLMENT STATUS|Age of child,EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

development:
  label.encounter.map: EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS
  concept: ENROLLMENT STATUS|Age of child,EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

test: &TEST
  label.encounter.map: EID VISIT|EID VISIT,ENROLLMENT STATUS|HIV STATUS AT ENROLLMENT,GIVE DRUGS|DISPENSING,PMTCT HISTORY|PMTCT HISTORY,NOTES|NOTES
  clinical.encounters.sequential.list: EID VISIT,ENROLLMENT STATUS,NOTES,PMTCT HISTORY,GIVE DRUGS
  clinical.encounters.display.list: EID VISIT;ENROLLMENT STATUS;NOTES;PMTCT HISTORY;GIVE DRUGS
  scope: ENROLLMENT STATUS|RECENT,NOTES|,GIVE DRUGS|,EID VISIT|TODAY,PMTCT HISTORY|EXISTS
  concept: ENROLLMENT STATUS|Age of child,EID VISIT|Weight,PMTCT HISTORY|ARVs In Labour
  label: ENROLLMENT STATUS|Enrollment Status,GIVE DRUGS|Give drugs

eid_visit: eid_protocol_patients

enrollment_status: eid_protocol_patients

notes: eid_protocol_patients

pmtct_history: eid_protocol_patients

give_drugs: eid_protocol_patients
